#!/bin/bash
    
apt update && apt upgrade -y
apt install git -y
pip3 install -U pip
git clone https://github.com/deepukumarpuri/JORANA /JORANA
cd /JORANA
pip3 install -U -r requirements.txt
python3 main.py
